# Generated by Django 5.1.1 on 2024-10-03 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptopApproval', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='laptoprequest',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='manager',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requestassignment',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
