# Generated by Django 5.1.1 on 2024-10-04 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptopApproval', '0002_employee_is_deleted_laptoprequest_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptopinventory',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
