# Generated by Django 5.1.1 on 2024-10-04 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptopApproval', '0003_laptopinventory_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptoprequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled')], default='Pending', max_length=10),
        ),
    ]
